-- UPDATE certificato pulito
UPDATE rentri_org_certificates
SET 
  certificate_pem = '-----BEGIN CERTIFICATE-----
MIIDGDCCAr+gAwIBAgIEBfYMfjAKBggqhkjOPQQDAjBXMQswCQYDVQQGEwJJVDET
MBEGA1UEChMKUkVOVFJJIE9yZzEWMBQGA1UECxMNUkVOVFJJIEFQSSBDQTEbMBkG
A1UEAxMSUkVOVFJJIEFQSSBDQSBERU1PMB4XDTI1MTIwMzE0MTIxMloXDTI3MTIw
MzE0MTIxMlowgZkxGTAXBgNVBC4TEFJFTlRSSS0xMDAwMTExMzQxJjAkBgNVBAMM
HVNDT1paQVJJTkkgRU1NQU5VRUwgU0FMVkFUT1JFMR8wHQYDVQRhDBZDRjpJVC1T
Q1pNTkwwNUwyMUQ5NjBUMSYwJAYDVQQKDB1TQ09aWkFSSU5JIEVNTUFOVUVMIFNB
TFZBVE9SRTELMAkGA1UEBhMCSVQwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARr
bwsxsr6/68S/2kvcYZYosVCOeqrMplwWdA9KOu5cDCzegNSgoMy4FcNFGbYy8AtQ
JjRW7uSsV8rJ3Ch6begMo4IBNDCCATAwDgYDVR0PAQH/BAQDAgbAMB8GA1UdIwQY
MBaAFHCuwTwtKx3Vpg+RvrF7yLt45QP3MEgGCCsGAQUFBwEBBDwwOjA4BggrBgEF
BQcwAoYsaHR0cHM6Ly9kZW1vYXBpLnJlbnRyaS5nb3YuaXQvY2EtcmVudHJpL2Nh
LzEwCQYDVR0TBAIwADAdBgNVHQ4EFgQUzX7avMMNhRMe3LY8lp9A0PrwrkYwHwYD
VR0lBBgwFgYIKwYBBQUHAwIGCisGAQQBgjcUAgIwJQYDVR0RBB4wHIEaUkVTQ1VF
TUFOQUdFUkBMRUdBTE1BSUwuSVQwQQYDVR0fBDowODA2oDSgMoYwaHR0cHM6Ly9k
ZW1vYXBpLnJlbnRyaS5nb3YuaXQvY2EtcmVudHJpL2NhLzEvY3JsMAoGCCqGSM49
BAMCA0cAMEQCID+xqvAbkrgKhEsbZ7NajlDd6IUPah3D2dfiN/J3bXqdAiAJPvIt
HY13k4f74Lspu+68ovZ2Q9E5KONMS70EzGvyEA==
-----END CERTIFICATE-----',
  private_key_pem = '-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgRguiZJUN2o/WexE8
7XtzFEkFhTUHhE/Oi4ivUiFm7ZehRANCAARrbwsxsr6/68S/2kvcYZYosVCOeqrM
plwWdA9KOu5cDCzegNSgoMy4FcNFGbYy8AtQJjRW7uSsV8rJ3Ch6begM
-----END PRIVATE KEY-----',
  updated_at = NOW()
WHERE cf_operatore = 'SCZMNL05L21D960T'
AND environment = 'demo';

-- Verifica
SELECT 
  id, cf_operatore, environment,
  SUBSTRING(certificate_pem, 1, 30) as cert_start,
  SUBSTRING(private_key_pem, 1, 30) as key_start
FROM rentri_org_certificates
WHERE cf_operatore = 'SCZMNL05L21D960T';
